### ISSUE TITLE
Select Multiple Generations at Once

### ISSUE THREAD

**Issue by Menardi** [Menardi/whosthatpokemon#1]
This is a feature that has been requested by a few people, and would certainly be nice to have.

Right now, only one generation can be chosen at a time to get Pokémon from. The randomisation of this is done by filling an array with numbers from the lowest number of that generation (e.g. 152 for Gen 2) to the highest (251 for Gen 2), then shuffling this. Adding support for multiple simultaneous generations should be a case of adding the numbers for all desired generations into this array and then shuffling it.

**Comment by Menardi** [comment]
Thanks to @D4RKONION for the hard work!

**Comment by D4RKONION** [comment]
Aw shucks :D
