### ISSUE TITLE
Pokemon Dex No. 803-809 Missing

### ISSUE THREAD

**Issue by KingLemmy072610** [Menardi/whosthatpokemon#11]
I downloaded the image repo from the website and Poipole, Naganadel, Blachepalon, Stakataka, Zeraora, Meltan, and Melmetal are missing. Would you be able to add the pokemon onto your live site, or at least your image repo. Thanks in advance!

**Comment by Menardi** [comment]
I've just added support for Gen 8, and added these missing Gen 7 pokémon in the process. If you download the zip file again, you will find all pokémon there.
