### ISSUE TITLE
Some suggestions that can make the game better (in my opinion)

### ISSUE THREAD

**Issue by Pomardinho** [Menardi/whosthatpokemon#21]
I love the game so much that I've even completed all 905 Pokémon in one streak a few days ago. Either way, I'd like to suggest some additions that can make long streaks better or just make the game even more enjoyable.

1. A chance to get a shiny form of the Pokémon. This chance could be very low if you have no streak, but keep increasing as you continue in a streak. Also, it could be a top chance so if you're on a very high streak the chance doesn't keep increasing more.
2. Another chance to get a Pokémon variation, such as Alola or Galar forms. There's no need to add new Pokémon, just to add a chance to get a variation if the Pokémon has one.
3. A selector that lets the user change the time between another Pokémon appears. Sometimes it's a bit boring to wait 3s every time you want to get a new Pokémon. 
I could help if it's needed, even tho I'm a beginner. 

Thanks for bringing out this awesome game <3.

**Comment by Menardi** [comment]
Thanks for your suggestions! The first two do sound like they'd be fun additions. The delay can be a bit annoying, but it gives time for the next Pokémon image to load. Although that was based on internet speeds several years ago when this first came out, so I'll see if it makes sense to speed it up now!

**Comment by Menardi** [comment]
I've released a new update so you can now press the Enter key to skip immediately to the next Pokémon. I think this gives users the right amount of control over how quickly they want to play, without needing to add any extra settings. Hope you like it!

I'll close this now to avoid duplicates, as the other suggestions are already covered in #20.

**Comment by Menardi** [comment]
@pressRtowin That makes sense, can you create a separate issue so I can keep track of it?
