### ISSUE TITLE
Generation swap not recognized between rounds

### ISSUE THREAD

**Issue by pedrosilva17** [Menardi/whosthatpokemon#24]
If you change the difficulty after guessing a pokémon (or giving up) and before the next round, it does so normally. However, the same doesn't apply to generations, where if you change them in that period, that change is ignored. This is fixed by changing to a *third* generation before giving up or guessing right (I said a "third" generation because it has to be different than the one you chose to swap to initially, otherwise it just gets ignored). Further changes made after guessing and before the following round are all ignored.

For example, if I swap to gen 7 from gen 1 during the aforementioned period, the generated pokémon will still be from gen 7. Changing to gen 6 before guessing fixes the problem, but changing to gen 6 and back to gen 1 in a single round (even before guessing) will still generate pokémon from gen 7.

I've left some examples below: Exploud found in gen 5 and Drampa in gen 1. You can see the changes were made before the round started because the "Your new settings will take effect for the next Pokémon" message is missing. This happens in every difficulty.

![image](https://user-images.githubusercontent.com/75742355/184539894-ff1ce7bb-ea3b-4e71-830e-443446f2a858.png)
![image](https://user-images.githubusercontent.com/75742355/184539918-aa805f65-f17d-431d-a298-2166ecb9723a.png)

Nitpicking aside, the website is a lot of fun and I enjoy testing my memory in there from time to time. Great work!

**Comment by Menardi** [comment]
This is an interesting one, nice find! In this case, the UI has become desynced from what the game is actually doing. I suspect there may be a few other places where this could be causing issues too. I'll have to think about it a bit, and see if there's a nice solution. Thanks for reporting it!

**Comment by pedrosilva17** [comment]
I was going to try to see where the problem was in the code, but looks like it was quickly solved. Glad to help!

**Comment by Menardi** [comment]
Yes, it turned out to be a much simpler fix than I expected! I just needed to refamiliarise myself with that part of the code. Thanks for the report. 🙂
