### ISSUE TITLE
Treasures of Ruin names formatted wrong

### ISSUE THREAD

**Issue by Magnezone1234** [Menardi/whosthatpokemon#29]
The names are currently as

Ting-lu
Chien-pao
Wo-chien
Chi-yu

Whereas they should be

Ting-Lu
Chien-Pao
Wo-Chien
Chi-Yu

The second part of the name is capitalized officially.

**Comment by sora10pls** [comment]
Where in the app do they format incorrectly? From what I see, their names are formatted correctly, like with Ho-Oh, Jangmo-o, and its evolutions.
![image](https://user-images.githubusercontent.com/17801814/206072386-193e50a8-b97d-4118-beb1-14edaeb8265c.png)

**Comment by Magnezone1234** [comment]
At the time when I wrote my question the english names appeared wrong when you guessed the answer but it seems to have been corrected since then.
Could have been my browser or something.
