### ISSUE TITLE
Gen 9 pokemon

### ISSUE THREAD

**Issue by gaberilde** [Menardi/whosthatpokemon#30]
The images for gen 9 pokemon have now been released on offical pokemon website now, so now you can replace the ones being used right now with the correct ones.

**Comment by sora10pls** [comment]
I intend on working on this soon. I'd like to inquire @Menardi first - the project currently uses internal numbering that Scarlet and Violet do, which skips 980 and 987. Now that we have official National Dex numbers, what are your thoughts on reordering everything to match the official numbers used for media? I wouldn't be opposed to submitting a PR to address this, and in the process, add in all the new art.

**Comment by Menardi** [comment]
@sora10pls Does this renumbering just affect Gen 9? If that's the case I think it makes sense to reorder them as per their new official numbering. I'm happy to follow your lead on this, whatever you think is the most sensible option. You're much more familiar with the data than I am. 😄

**Comment by sora10pls** [comment]
That is correct, only Gen 9 will be affected.

When I get home from work today, I’ll start addressing this and submit a pull request to solve this issue and adjust the numbering whenever it’s done.
