### ISSUE TITLE
Idea: add a timer

### ISSUE THREAD

**Issue by gaberilde** [Menardi/whosthatpokemon#31]
When you join the site you should get a timer before the pokemon shows up to give you time to click into the site and get ready to start typing it would help quite a bit for when you first load the site.

**Comment by Menardi** [comment]
Thanks for your suggestion! That is a good point that on first load the user might not be ready for the timer to start. I'll keep this in mind when I'm working on new features next.

**Comment by gaberilde** [comment]
Thanks it helps people like me with slow WiFi 👍
