### ISSUE TITLE
Gen:9 Wrong Image

### ISSUE THREAD

**Issue by EDude0629** [Menardi/whosthatpokemon#33]
Some of the Generation 9 Pokémon will show an image that doesn’t match the correct answer. For example, the website would show an image of Frigibax, but when I click the “I don’t know” button, it will tell me the correct answer is “Toeadscruel”. The weird part is that it’s only happening for SOME
Generation 9 Pokémon, all other generations work just fine. It was also fine earlier this morning as well as yesterday. I tried closing and reopening the website (didn’t work) as well as closing my browser (also didn’t work). I’m trying to use the website to better memorize the Generation 9 Pokémon since this is my first time being an active Pokémon player when a new generation released, so if this could get fixed as soon as possible, that would be greatly appreciated. Thanks!
![825E3563-DBB3-4812-92DA-B74EC286111D](https://user-images.githubusercontent.com/123588286/214717927-f3a9aa20-85c5-49e8-901f-7260002c94c5.png)

**Comment by EDude0629** [comment]
I don’t think this is an issue with the website universally. I was at my friends house the other day and it was just fine on his computer.

**Comment by Menardi** [comment]
Thanks for reporting this. We recently changed the numbers of Gen 9 Pokémon to match the National Dex numbering (https://github.com/Menardi/whosthatpokemon/issues/30). I think what's probably happening here is that the browser has cached the images based on the previous numbers. If the site works correctly in a private window, then this is almost certainly the cause.

You should be able to fix this issue by clearing your browser's cache or history. Could you let me know if that fixes it for you?
