### ISSUE TITLE
[Bug] Generation loops after completion

### ISSUE THREAD

**Issue by sora10pls** [Menardi/whosthatpokemon#34]
`generationFinishedMessage` is never shown to the user after all Pokémon in your selected generation have been guessed. Unsure of when exactly this quirk made its way into the project, but it might have been some time after Generation 9 support was added (my initial tests around SV launch didn't have this issue).

Example attached is of a run where only Generation 6 was selected, and after I went through all 72 species, it started over again.
![image](https://user-images.githubusercontent.com/17801814/216345680-e3bd833c-b8c5-4d48-96f7-4ef007bf5924.png)

**Comment by Menardi** [comment]
Good spot! It looks like I probably caused this when fixing https://github.com/Menardi/whosthatpokemon/issues/24. I had also fixed an issue where if a user selected only Gen 8 and 9, on an unsupported difficulty, they didn't see a message at all. Both of these fixes combined to cause new numbers to be generated immediately when there was no next Pokémon available to show, so the end of generation message was never shown.

I've fixed this by skipping the generation of new numbers if the user has reached the end of the generation, and it works correctly now from my testing. This part of the code is starting to look quite messy and hard to understand, but I hope I've gotten it right!
