### ISSUE TITLE
Track more stats 

### ISSUE THREAD

**Issue by pressRtowin** [Menardi/whosthatpokemon#36]
Just an idea I had. Add a stats page with charts or something. Was thinking along the lines of being able to see which pokemon you got wrong most frequently so you can focus on memorizing those.

**Comment by Menardi** [comment]
I have considered adding some extra stats in the past, but haven't had the time to implement it. There's quite a lot of possibility here, so I'd need to think about what would actually be interesting and useful. I'll leave this open as something I can come back to in future when I have some time to work on it.

**Comment by davud27** [comment]
I wrote some code to add all types to each pokemon and show it during the game as a hint. I'll see what I can do once you rewrite the core code.
