### ISSUE TITLE
Idea: Add options where it is possible to change the time between appearance of Pokemon

### ISSUE THREAD

**Issue by anon01001001** [Menardi/whosthatpokemon#40]
Every time players guess the name of a Pokemon correctly, it is necessary to wait 3 seconds until the next Pokemon appears. It would be interesting if there were options to change this... like making pokemon appear instantly etc, and/or maybe even making the base time (3 seconds) gradually decrease with each hit, thus making players feel like they are improving in speed as they learn the names of Pokemon and hit the names faster and faster.

**Comment by blakethorne5112** [comment]
I second this, it becomes a chore to wait inbetween if you're naming every pokemon

**Comment by Menardi** [comment]
Thanks for your feedback! I've released an update so now you can press the Enter key to skip immediately to the next Pokémon. I think this gives users the right amount of control over how quickly they want to play, without needing to add any extra settings. Hope you like it!

**Comment by anon01001001** [comment]
> Thanks for your feedback! I've released an update so now you can press the Enter key to skip immediately to the next Pokémon. I think this gives users the right amount of control over how quickly they want to play, without needing to add any extra settings. Hope you like it!

Splendid!
