### ISSUE TITLE
Add a reset button

### ISSUE THREAD

**Issue by KINGdom20213** [Menardi/whosthatpokemon#41]
I would love if a reset button was added, so I can try to beat my best a lot more times than currently possible. A reset button would add more variety into the gameplay. Thanks and have a great day!

**Comment by Menardi** [comment]
Thanks for your feedback. I don't have plans to add a reset button, as I want to keep the site relatively simple. But, you could manually reset your stats by clearing your browser's data for `gearoid.me`. If you're familiar with the Javascript Console in your browser's Developer Tools, you could also run `localStorage.clear()` on the site to clear your stats.
