### ISSUE TITLE
Game Finished Early

### ISSUE THREAD

**Issue by professionalpro1** [Menardi/whosthatpokemon#47]
I got to 808 and it finished even though there are 1000+ pokemon
![image](https://github.com/Menardi/whosthatpokemon/assets/136689697/cc2875f9-27f4-403f-a0d1-bc678cf8fb3a)

**Comment by Menardi** [comment]
Thanks for reporting this issue, I haven't seen this happen before. I'm working on a rewrite of the codebase so hopefully this will be fixed once that is done.

**Comment by Menardi** [comment]
I've deployed the rewritten codebase today. I tested for this exact scenario and couldn't reproduce it, so I'll close this as fixed. If it happens again, feel free to re-open this.
