### ISSUE TITLE
[Request] Update Pokémon Artwork

### ISSUE THREAD

**Issue by sora10pls** [Menardi/whosthatpokemon#48]
Now that official artwork has been released for all of the Scarlet/Violet DLC Pokémon, we can now update the project with this artwork, as opposed to using renders from Pokémon HOME.

The artwork can be [downloaded here](https://mega.nz/file/wMc0RCaR#JwwoD0Z3BBVmwZ3nQWR34eb5Ka7ZX86ZAEBS45NvzhU) (will be deleted once pushed). Several have been updated to remove the white glow provided by official press releases, courtesy of Bulbapedia contributors.

Example:
![image](https://github.com/Menardi/whosthatpokemon/assets/17801814/c1c58425-57ce-4ed3-a05d-8a03e038a2cc)

**Comment by Menardi** [comment]
This is deploying now. Thank you as always @sora10pls! 🙏
