### ISSUE TITLE
A way to pause the game without ending the streak or adding a statistical outlier to your stats.

### ISSUE THREAD

**Issue by pressRtowin** [Menardi/whosthatpokemon#51]
Sometimes you just gotta walk away from your computer for whatever reason, and it'd be nice to be able to do that (especially when tackling longer challengers like a full run of all 9 generations) without losing your streak or the next Pokémon being recorded as taking you 92387203489273 seconds to guess.

Your only options now are to click "I don't know" when you get back, skipping that Pokémon and ending your streak (Edit: and also affecting your stats as of the latest update), or to just enter it when you get back, adding a huge spike to your time.

Maybe a keyboard shortcut that you can press as an alternative to "Enter" during the countdown, that instead pauses the game and doesn't show the next Pokémon until you come back and press "Enter" again?

Or whatever other idea you have for implementing something similar.

**Comment by Menardi** [comment]
Thanks, I'm glad you like the update, it just went up today!

One big change in the update is that the game state is now saved across reloads. This means that your streak is saved across sessions, and you'll be going through one set of Pokémon until you reach the end, or when you change your settings. The timer starts when you re-open the page, so you should be able to avoid any huge time spikes. Even if you accidentally leave the tab open, just reloading the page would reset the timer and avoid a spike.

Also, another change I made with this update is that the max time recorded for any guess is 90 seconds, to avoid skewing stats with one big outlier.

Hope you find those updates useful!

**Comment by Menardi** [comment]
The opportunity to cheat did cross my mind! But if someone is willing to cheat their own times in a single-player game, I'm not going to try too hard to stop them. 😅 

I'll close this issue since it seems to be resolved with today's update.
