### ISSUE TITLE
Does not go to the next Pokemon after guessing right

### ISSUE THREAD

**Issue by JKizz** [Menardi/whosthatpokemon#6]
Have to refresh the page to get a new Pokemon. Not progressing to the next Pokemon also prevents the changing in difficulty or any other settings. Also happens on mobile.

**Comment by Menardi** [comment]
Thanks for the report. Is this still happening to you? I was doing a server update around the time you reported this, which could have caused the issue.

If it is still happening, could you let me know what browser you're using, and if it happens for every Pokémon?

**Comment by JKizz** [comment]
Yeah this is still happening. I've tested it on Firefox, Chrome, and Safari (mobile).
It basically looks like this image without changing.
![test](https://user-images.githubusercontent.com/32278283/51054277-5a974f00-15aa-11e9-9ae5-159ec1d269a9.PNG)

**Comment by Menardi** [comment]
I think it was caused by me removing Google Analytics, which was keeping track of correct and incorrect answers. I have fixed it now. Can you try a hard reload (Ctrl + R), and try it again?

**Comment by JKizz** [comment]
It works now! Thank you.
