### ISSUE TITLE
Problem in the french version

### ISSUE THREAD

**Issue by Fakepowa1** [Menardi/whosthatpokemon#8]
So I've had close to no problem while playing this game in its french version, but there's one pokemon that doesn't work. It's Litten, if you type in "Flamiaou" (which is its french name) into the box, it doesn't mark it as right. However if you click "I don't know", the answer is... "Flamiaou".

**Comment by Menardi** [comment]
Thanks for reporting the issue, I appreciate it. It turns out that Flamiaou in French had some hidden characters in it. So, when the game checked if your answer was correct, it was essentially checking if `Flamiaou` was the same as `Flamiaou--`, which of course it isn't. I have removed these hidden characters now, so next time you come across Flamiaou, you will be correct. :smiley:

**Comment by Fakepowa1** [comment]
Thank you for that correction!
I went through all the pokemons yesterday and apparently bidoof's french translation (Keunotor) has some hidden characters in it as well because I got the same problem, all the other ones work though :)

**Comment by Menardi** [comment]
According to [Bulbapedia](https://bulbapedia.bulbagarden.net/wiki/Bidoof_(Pok%C3%A9mon)#In_other_languages), where I got the translations from, it is `Keunottor`, with two `t`s,, not one, which could be why it wasn't showing as correct for you?

**Comment by Fakepowa1** [comment]
Well it's weird that Bulbapedia made that mistake,  but, if you dare to trust a stranger on the internet, it's definetely with only one T. Try googling Keunottor and it shoukd correct it :)

**Comment by Menardi** [comment]
You are correct! The [official site](https://www.pokemon.com/fr/pokedex/keunotor) spells it with one `t`. I have fixed it, and also edited Bulbapedia so nobody else makes the same mistake. :smile:

**Comment by Fakepowa1** [comment]
Thank you very much for your quick responses and corrections!
If you ever want to make the french version perfect, I can make a list of little tweaks :)

**Comment by Menardi** [comment]
By all means, please do make a list of any other corrections. If you are familiar with Javascript, you may create a pull request with the changes here on GitHub. If not, please open a new Issue with a list of your suggested changes. Thanks!
