### ISSUE TITLE
Translation errors in the french version

### ISSUE THREAD

**Issue by Fakepowa1** [Menardi/whosthatpokemon#9]
Hey it's me again !

As I don't know anything about coding, I'll just list the problems (which are mostly translation based) in the french version of the game as you proposed and I'll let you do the changes, sorry for that !

For the HUD I'll go from left to right and top to bottom.

On the left : 
Generations and difficulty are correct.
For the ''Spelling'', ''Exact'' translates to ''Exacte'' (missing an E as Orthographe is a female noun).
''Sound'' translates to ''Son'' in French.

In the middle : 
''Who's that Pokemon ?'' translates to ''Quel est ce Pokémon?''.
''Also known as'' translates to ''Aussi connu sous le nom de'' (quite the lenghty translation but the most accurate one).
''Next Pokemon in...'' translates to ''Pokémon suivant dans...''

On the right :
''Streak'' translates to ''Consécutif'' (missing CU).
In the chrono section, ''Previous'' translates to ''Précédent'' (you have one E too much there).

Now for the last little things, it's kinda hard to explain as I don't know how code works. 
You've probably realized that many french names of Pokemons have an accent on some vowels (é, è, etc.). For many of those, juste writing the vowel works (ie. for Charmander, if you write salameche, it will be correct even if the spelling is salamÈche). 
This works for most of the Pokemons, except for one witch is Phantump. The french name is Brocélôme and if you write brocelome it's not considered correct. You have to at least write brocelôme to get it right, so e/é is alright but O is not considered the same as Ô.
Also there's a ç in French which is another character for c used before some vowels to change the sounding of the word. Just like for the o/ô, c is not recognised as ç, which is used for two Pokemons (Bergmite and Escavalier -> grelaçon and lançargot).
I don't know how the game recognizes E's as é, è or even ê, but if you could make it as the game recognizes o as ô and c as ç it would be awesome !

Voilà ! I think I've listed every little thing I've come across while playing the game !
If I ever find something else, I'll be sure to tell you about it, and if you implement the 8th generation in the game once the new games come out, I'll be sure to give you feedback if there's anything aswell !

Thank you again for your ealier modifications in the french version and the ones this post will make you do :p

**Comment by Menardi** [comment]
Merci beaucoup! I've fixed all of the spelling mistakes. I have also made answers ignore circumflexes and cédilles, so you won't need to worry about getting the accents right anymore. Thanks for all your feedback!
